// generated by Fast Light User Interface Designer (fluid) version 1,0400

#ifndef main_window_h
#define main_window_h
#include <FL/Fl.H>
#include "OutlineTree.h"
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Group.H>
extern OutlineTree *g_pTree;
Fl_Double_Window* make_window();
#endif
